import { useState } from 'react';
import { InputForm } from './components/InputForm';
import { SimulationChart } from './components/SimulationChart';
import type { SimulationParams } from './types';

function App() {
  const [params, setParams] = useState<SimulationParams>({
    fee: 2000,
    farmers: [
      { id: '1', name: 'Farmer A', area: 10 },
      { id: '2', name: 'Farmer B', area: 5 }
    ],
    pumpOwnerArea: 2,
    areaUnit: 'bigha',
    electricity: 15000,
    waterReductionRate: 20,
    returnRate: 50,
  });

  const handleParamChange = (key: keyof SimulationParams | Partial<SimulationParams>, value?: any) => {
    if (typeof key === 'object') {
      setParams((prev) => ({ ...prev, ...key }));
    } else if (value !== undefined) {
      setParams((prev) => ({ ...prev, [key]: value }));
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden">
      {/* Background decorations */}
      <div className="absolute top-0 left-0 w-full h-[400px] bg-gradient-to-br from-blue-500/10 via-emerald-500/10 to-transparent -z-10 pointer-events-none" />
      <div className="absolute top-[-100px] right-[-100px] w-96 h-96 bg-blue-400/20 rounded-full blur-3xl -z-10 pointer-events-none" />
      <div className="absolute bottom-[-100px] left-[-100px] w-96 h-96 bg-emerald-400/20 rounded-full blur-3xl -z-10 pointer-events-none" />

      <div className="max-w-6xl mx-auto px-4 py-12">
        <header className="mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-emerald-600 mb-4 tracking-tight">
            Irrigation Water Reduction Simulator
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Simulate how the profit (electricity savings) generated by reducing irrigation water is distributed between farmers and pump owners.
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch mb-12">
          <div className="lg:col-span-4">
            <InputForm params={params} onChange={handleParamChange} />
          </div>
          <div className="lg:col-span-8">
            <SimulationChart params={params} />
          </div>
        </div>

        {/* Calculation Formulas Section */}
        <div className="bg-white/60 backdrop-blur-md rounded-2xl p-8 border border-slate-200/60 shadow-sm max-w-4xl mx-auto">
          <h3 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
            <span className="bg-indigo-100 text-indigo-600 p-2 rounded-lg">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg>
            </span>
            Calculation Formulas
          </h3>
          
          <div className="space-y-8 text-slate-600">
            <div>
              <h4 className="font-semibold text-slate-800 mb-3 text-lg border-b border-slate-200 pb-2">1. Base Variables</h4>
              <ul className="space-y-3 ml-2">
                <li className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-3">
                  <span className="font-medium text-slate-700 min-w-[220px]">Total Area</span>
                  <code className="bg-slate-100 text-pink-600 px-2 py-0.5 rounded text-sm">= Sum of all Farmers' areas + Pump Owner's area</code>
                </li>
                <li className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-3">
                  <span className="font-medium text-slate-700 min-w-[220px]">Total Fee from all Farmers</span>
                  <code className="bg-slate-100 text-pink-600 px-2 py-0.5 rounded text-sm">= Fee × Sum of all Farmers' areas</code>
                </li>
                <li className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-3">
                  <span className="font-medium text-slate-700 min-w-[220px]">Farmers' Electricity Share</span>
                  <code className="bg-slate-100 text-pink-600 px-2 py-0.5 rounded text-sm">= Total Electricity bill × (Sum of all Farmers' areas / Total Area)</code>
                </li>
                <li className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-3">
                  <span className="font-medium text-slate-700 min-w-[220px]">New Electricity Cost (Farmers' Share)</span>
                  <code className="bg-slate-100 text-pink-600 px-2 py-0.5 rounded text-sm">= Farmers' Electricity Share × (1 - Water Reduction Rate / 100)</code>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-slate-800 mb-3 text-lg border-b border-slate-200 pb-2">2. Profit Calculations</h4>
              <ul className="space-y-4 ml-2">
                <li className="bg-emerald-50/50 p-4 rounded-xl border border-emerald-100">
                  <span className="block font-bold text-emerald-800 mb-2">🧑‍🌾 Individual Farmer's Profit</span>
                  <code className="bg-white border border-emerald-200 text-emerald-700 px-3 py-1.5 rounded-lg text-sm block overflow-x-auto">
                    = (Fee × Individual Farmer's area) × (Return Rate / 100)
                  </code>
                  <p className="text-sm text-emerald-600 mt-2">Each farmer receives a discount on their individual water fee equivalent to the Return Rate.</p>
                </li>
                <li className="bg-indigo-50/50 p-4 rounded-xl border border-indigo-100">
                  <span className="block font-bold text-indigo-800 mb-2">⚙️ Pump Owner's Profit</span>
                  <code className="bg-white border border-indigo-200 text-indigo-700 px-3 py-1.5 rounded-lg text-sm block overflow-x-auto">
                    = {`{ Total Fee from all Farmers × (1 - Return Rate / 100) }`} - New Electricity Cost (Farmers' Share)
                  </code>
                  <p className="text-sm text-indigo-600 mt-2">The pump owner's profit is the remaining fee collected from all farmers after their individual discounts, minus the new reduced electricity cost for the farmers' total portion.</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
